weeklytrackchart:
  \@attr:
    user: str
    from: int date
    to: int date
  track:
    - \@attr:
        rank: int 1 to n
      artist:
        mbid: '[a-z0-9\-]+'
        \#text: str
      mbid: '[a-z0-9\-]+'
      url: str
      image: whocares
      name: str
      playcount: int


track_info:
  <mbid>:
    name: str
    mbid: str
    url: str
    duration: int (milliseconds)
    artist:
      name: str
      mbid: str
      url: str
    album:
      artist: str
      title: str
      mbid: str
      url: str
      \@attr:
        position: int
    userplaycount: int
    toptags:
      tag:
        - name: str
          url: str
